### ISSUE TITLE
Automatically create GitHub tag whenever Cargo.toml gets a version bump

### ISSUE THREAD

**Issue by nilsiker** [nilsiker/godam#21]
It would be nice to automate this, and solely control the trigger of a new release by actually bumping the Cargo.toml.

It needs some thought, and maybe there are good reasons not to do this, but I still want to document the idea.

An action skeleton could look like

```yaml
name: Tag Version on Cargo.toml Update

on:
  push:
    branches:
      - main
    paths:
      - 'Cargo.toml'

jobs:
  tag_version:
    runs-on: ubuntu-latest

    steps:
      # checkout repo
      # set up Rust
      # get version from cargo using grep
      # check if tag exists
      # create tag if not exists, triggering my release action
```
